/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#9a0021",
        "primary-container": "#c41230",
        "primary-fixed": "#ffdad9",
        "primary-fixed-dim": "#ffb3b2",
        "on-primary": "#ffffff",
        "on-primary-container": "#ffd6d5",
        "on-primary-fixed": "#410008",
        "on-primary-fixed-variant": "#92001e",
        
        "secondary": "#b52619",
        "secondary-container": "#ff5c47",
        "secondary-fixed": "#ffdad4",
        "secondary-fixed-dim": "#ffb4a8",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#610000",
        "on-secondary-fixed": "#410000",
        "on-secondary-fixed-variant": "#920703",
        
        "tertiary": "#5f4716",
        "tertiary-container": "#795f2b",
        "tertiary-fixed": "#ffdea4",
        "tertiary-fixed-dim": "#e4c285",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffdb9c",
        "on-tertiary-fixed": "#261900",
        "on-tertiary-fixed-variant": "#5a4312",
        
        "surface": "#fcf9f8",
        "surface-card": "#FFFFFF",
        "surface-muted": "#F5F5F5",
        "surface-bright": "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e5e2e1",
        "surface-variant": "#e5e2e1",
        "surface-tint": "#bd092c",
        
        "bg-base": "#FDF8F0",
        "background": "#fcf9f8",
        "on-background": "#1c1b1b",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#5c403f",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f3f0ef",
        "inverse-primary": "#ffb3b2",
        
        "text-primary": "#1A1A1A",
        "text-secondary": "#666666",
        "border-subtle": "#EBE5DF",
        "border-gold": "#C9A96E",
        "outline": "#906f6e",
        "outline-variant": "#e4bdbc",
        
        "halal-green": "#15803D",
        "halal-green-bg": "#DCFCE7",
        "line-brand": "#06C755",
        "paypay-brand": "#FF0033",
        "badge-discount": "#E11D48",
        "badge-tax-gray": "#4B5563",
        
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        "sans": ["'Plus Jakarta Sans'", "Inter", "-apple-system", "BlinkMacSystemFont", "'Segoe UI'", "Roboto", "sans-serif"],
        "display": ["'Outfit'", "'Plus Jakarta Sans'", "sans-serif"],
        "heading": ["'Outfit'", "'Plus Jakarta Sans'", "sans-serif"],
        "poppins": ["'Poppins'", "'Plus Jakarta Sans'", "sans-serif"],
        "serif": ["'Outfit'", "'Plus Jakarta Sans'", "sans-serif"],
      },
      spacing: {
        "space-2xs": "0.125rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-base": "1rem",
        "space-lg": "1.25rem",
        "space-xl": "1.5rem",
        "space-2xl": "2rem",
        "space-3xl": "3rem",
        "space-4xl": "4rem",
        "layout-max-width": "1280px",
        "gutter-desktop": "1.5rem",
        "gutter-mobile": "1rem",
      }
    },
  },
  plugins: [],
}
